#in ms (1s = 1000ms)
tax-time: 1000000
#in ticks (1s = 20t)
update-time-tax-time: 120
#block number : percentage
#block number 0 is the default if the border has not been found
border-tax:
  - "0:10"
  - "20:12"
  - "40:12.3"